on:
  workflow_call:
    inputs:
      dry-run:
        description: "Don't delete images, only print names and URLs"
        required: true
        type: boolean

permissions: read-all

jobs:
  cleanup:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        repository:
          - ddterm/gnome-shell-pod
          - ddterm/ci-docker-image
          - ddterm/gnome-shell-image

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci

      - id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}
          owner: ${{ github.repository_owner }}
        if: ${{ github.secret_source == 'Actions' }}

      - run: >-
          ./cleanup.js
          ${{ inputs.dry-run && '-n' || '' }}
          -r "${{ matrix.repository }}"
          -o "${{ github.repository_owner }}"
          --log-level ${{ runner.debug && 'debug' || 'info' }}
          -j4
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token || github.token }}
