on:
  workflow_call:
    inputs:
      dry-run:
        description: "Don't delete images, only print names and URLs"
        required: true
        type: boolean

    secrets:
      packages-api-token:
        description: "A personal access token with packages:delete permission"
        required: true

jobs:
  cleanup:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        repository:
          - ddterm/gnome-shell-pod
          - ddterm/ci-docker-image

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci

      - run: >-
          ./cleanup.js
          ${{ inputs.dry-run && '-n' || '' }}
          -t "${{ secrets.packages-api-token }}"
          -r "${{ matrix.repository }}"
          -o "${{ github.repository_owner }}"
          -j4
