name: pr

on:
  pull_request:

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
    if: >-
      startsWith(github.event.pull_request.head.ref, 'renovate/')
      || github.event.pull_request.base.repo.node_id != github.event.pull_request.head.repo.node_id
