name: schedule

on:
  workflow_dispatch:
  schedule:
    - cron: 34 12 * * *

concurrency: ${{ github.workflow }}/${{ github.ref }}

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/cleanup.yml
    secrets: inherit
    with:
      dry-run: false
