name: schedule

on:
  workflow_dispatch:
  schedule:
    - cron: 34 12 * * *

concurrency: ${{ github.workflow }}/${{ github.ref }}

jobs:
  test:
    uses: ./.github/workflows/cleanup.yml

    with:
      dry-run: false

    secrets:
      packages-api-token: ${{ secrets.DELETE_PACKAGES_TOKEN }}
