name: test

on:
  workflow_dispatch:
  workflow_call:

concurrency: ${{ github.workflow }}/${{ github.ref }}

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/cleanup.yml
    secrets: inherit
    with:
      dry-run: true
