on:
  workflow_dispatch:
  workflow_call:

concurrency: ${{ github.workflow }}/${{ github.ref }}

jobs:
  gnome-shell-pod:
    uses: ./.github/workflows/cleanup.yml

    with:
      dry-run: true
      repository: ddterm/gnome-shell-pod
      owner: ddterm

    secrets:
      packages-api-token: ${{ secrets.DELETE_PACKAGES_TOKEN_RO }}

  ci-docker-image:
    uses: ./.github/workflows/cleanup.yml

    with:
      dry-run: true
      repository: ddterm/ci-docker-image
      owner: ddterm

    secrets:
      packages-api-token: ${{ secrets.DELETE_PACKAGES_TOKEN_RO }}
